import Head from 'next/head';
import Image from 'next/image';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Button, EditIcon } from '@/components/mui';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <Heading component='h2'>Contact Us</Heading>
          <Button variant="contained">
            <EditIcon />
            Button
          </Button>
        </Layout>
        <footer></footer>
      </div>
    </>
  );
}
