import Head from 'next/head';
// import Image from 'next/image';
import { Geist, Geist_Mono } from 'next/font/google';
import { Button, EditIcon } from '@/components/mui';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <Heading h1>Home Page</Heading>
          <Paragraph>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, ab pariatur rerum rem deleniti eveniet fuga consequatur delectus corrupti porro consectetur blanditiis at culpa suscipit aperiam accusamus doloremque. Ducimus, reiciendis.</Paragraph>
          <Button variant="contained">
            <EditIcon />
            Button
          </Button>
        <footer></footer>
      </Layout>
    </>
  );
}
